# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: conf.py

formats: all

python:
  version: 3.7
  install:
    - requirements: requirements.txt
