name: "Bug report"
description: Create a report to help us improve the Python devguide
title: "Bug: <title>"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > This repo is for the [Python devguide](https://devguide.python.org/).
        > If you are reporting a bug for the Python language or
        > CPython interpreter, then use the
        > [CPython issue tracker](https://github.com/python/cpython/issues) instead.

  - type: textarea
    id: bug_description
    attributes:
      label: "Describe the bug"
      description: A clear and concise description of what the bug is and, optionally, what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: Add any other context about the problem here.
    validations:
      required: false
