name: "Feature request"
description: Suggest an idea for the Python devguide
title: "Feature: <title>"
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > This repo is for the [Python developer's guide](https://devguide.python.org/).
        > If you are requesting an enhancement for the Python language or
        > CPython interpreter, then use the
        > [CPython issue tracker](https://github.com/python/cpython/issues) instead.

  - type: textarea
    id: feature_description
    attributes:
      label: "Describe the enhancement or feature you would like"
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you have considered"
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
