gantt
    dateFormat  YYYY-MM-DD
    title       Python release cycle
    axisFormat  %Y

    section Python 2.6
    end-of-life               :crit,   python2.6, 2008-10-01,2013-10-29

    section Python 3.0
    end-of-life               :crit,   python3.0, 2008-12-03,2009-06-27

    section Python 3.1
    end-of-life               :crit,   python3.1, 2009-06-27,2012-04-09

    section Python 2.7
    end-of-life               :crit,   python2.7, 2010-07-03,2020-01-01

    section Python 3.2
    end-of-life               :crit,   python3.2, 2011-02-20,2016-02-20

    section Python 3.3
    end-of-life               :crit,   python3.3, 2012-09-29,2017-09-29

    section Python 3.4
    end-of-life               :crit,   python3.4, 2014-03-16,2019-03-18

    section Python 3.5
    end-of-life               :crit,   python3.5, 2015-09-13,2020-09-30

    section Python 3.6
    end-of-life               :crit,   python3.6, 2016-12-23,2021-12-23

    section Python 3.7
    security               :done,   python3.7, 2018-06-27,2023-06-27

    section Python 3.8
    security               :done,   python3.8, 2019-10-14,2024-10-01

    section Python 3.9
    security               :done,   python3.9, 2020-10-05,2025-10-01

    section Python 3.10
    bugfix               :active,   python3.10, 2021-10-04,2026-10-01

    section Python 3.11
    bugfix               :active,   python3.11, 2022-10-24,2027-10-01

    section Python 3.12
    features               :   python3.12, 2023-10-02,2028-10-01
