flowchart TD
    report[Received a report...]
    via_security_at_python_dot_org[...via security@python.org?]
    psrt_admin_review[PSRT admin reviews email]
    email_reject[Reject]
    email_accept[Accept]
    open_via_ghsa[PSRT asks reporter to open via GHSA]
    via_ghsa[...via GHSA]
    ghsa_triage[GHSA in state “Triage”]

    report-->via_security_at_python_dot_org
    via_security_at_python_dot_org-->psrt_admin_review
    psrt_admin_review-->email_reject
    psrt_admin_review-->email_accept
    email_accept-->open_via_ghsa
    open_via_ghsa-->ghsa_triage
    report-->via_ghsa
    via_ghsa----->ghsa_triage
