name: Tests

on: [pull_request, push, workflow_dispatch]

env:
  FORCE_COLOR: 1

permissions: {}

jobs:
  test:
    name: Check build, markup, and links
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3"
      - name: Install uv
        uses: hynek/setup-cached-uv@4300ec2180bc77d705e626a34e381b81a4772c51 # v2.5.0
      - name: Build docs
        run: make html
      - name: Link check
        run: make linkcheck
        continue-on-error: true
