name: Tests

on: [pull_request, push, workflow_dispatch]

env:
  FORCE_COLOR: 1

permissions: {}

jobs:
  test:
    name: Check build, markup, and links
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3"
      - name: Install uv
        uses: hynek/setup-cached-uv@34e35d30f1ebc7421a5cc733bca38dcc62603960 # v2.6.0
      - uses: sphinx-doc/github-problem-matcher@1f74d6599f4a5e89a20d3c99aab4e6a70f7bda0f # v1.1
      - name: Build docs
        run: make html
      - name: Link check
        run: make linkcheck
        continue-on-error: true
