name: Test release cycle

on: [pull_request, push, workflow_dispatch]

env:
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3"

      - name: Generate release cycle output
        run: python -I -bb -X dev -X warn_default_encoding -W error _tools/generate_release_cycle.py

      - name: Check for differences
        run: |
          git add .
          git status
          git diff --staged
          test $(git status --porcelain | wc -l) = 0
