name: Translations

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Generate translation templates
        run: |
          make translations
      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add locales/**/*.po
          git commit -m "Update translations" --allow-empty
          git push
